apiVersion: customresource.catcode.mw/v1alpha1
kind: ResourceDefinition
metadata: 
  name: ApplicationResourceDefinition
spec:
  group: templating.catcode.mw
  plural: applications
  singular: application
  kind: Application
  versions: 
    - name: v1alpha1
      schema:
        openAPISchemaV3:
          type: object
          properties:
            apiVersion:
              type: "string"
            kind:
              type: "string"
              const: "Application"
            metadata:
              type: "object"
              properties:
                name:
                  type: "string"
                description:
                  type: "string"
              required:
                - name
                - description
            spec:
              type: "object"
              properties:
                owner:
                  type: "string"
              required:
                - owner
        required:
          - apiVersion
          - kind
          - metadata
          - spec
