apiVersion: api.catcode.io/v1alpha1
kind: ResourceDefinition
metadata: 
  name: ApplicationResourceDefinition
spec:
  group: templating.catcode.io
  names:
    plural: applications
    singular: application
    kind: Application
  versions: 
    - name: v1alpha1
      schemaVersion: openAPISchemaV3
      schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              system: 
                type: string
              owner:
                type: string
            required:
              - owner
              - system
      required:
        - spec
