apiVersion: customresource.catcode.mw/v1alpha1
kind: ResourceDefinition
metadata: 
  name: ComponentResourceDefinition
spec:
  group: templating.catcode.mw
  plural: components
  singular: component
  kind: Component
  versions: 
    - name: v1alpha1
      schema:
        openAPISchemaV3:
          type: object
          properties:
            apiVersion:
              type: "string"
            kind:
              type: "string"
              const: "Component"
            metadata:
              type: "object"
              properties:
                description:
                  type: "string"
                system:
                  type: "string"
                application:
                  type: "string"
                deployableUnit:
                  type: "string"
                tags:
                  type: "array"
                  items:
                    type: "string"
                version:
                  type: "string"
                  pattern: "^\\d+\\.\\d+\\.\\d+$"
              required:
                - description
                - system
                - application
                - deployableUnit
                - version
            spec:
              type: "object"
              properties:
                type:
                  type: "string"
                lifecycle:
                  type: "string"
                owner:
                  type: "string"
                dependecies:
                  type: "array"
                  items:
                    type: "string"
              required:
                - type
                - lifecycle
                - owner
                - dependecies
        required:
          - apiVersion
          - kind
          - metadata
          - spec
