apiVersion: api.catcode.io/v1alpha1
kind: ResourceDefinition
metadata: 
  name: ComponentResourceDefinition
spec:
  group: core.catcode.io
  names:
    plural: components
    singular: component
    kind: Component
  versions: 
    - name: v1alpha1
      schema:
        openAPISchemaV3:
          type: object
          properties:
            apiVersion:
              type: "string"
            kind:
              type: "string"
              const: "Component"
            metadata:
              type: "object"
              properties:
                version:
                  type: "string"
                  pattern: "^\\d+\\.\\d+\\.\\d+$"
              required:
                - version
            spec:
              type: "object"
              properties:
                system:
                  type: "string"
                application:
                  type: "string"
                tags:
                  type: "array"
                  items:
                    type: "string"
                type:
                  type: "string"
                lifecycle:
                  type: "string"
                owner:
                  type: "string"
                dependecies:
                  type: "array"
                  items:
                    type: "string"
              required:
                - type
                - lifecycle
                - owner
                - dependecies
        required:
          - metadata
          - spec
