apiVersion: api.catcode.io/v1alpha1
kind: ResourceDefinition
metadata: 
  name: ComponentResourceDefinition
spec:
  group: catcode.io
  names:
    plural: components
    singular: component
    kind: Component
  versions: 
    - name: v1alpha1
      schemaVersion: openAPISchemaV3
      schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              tags:
                type: array
                items:
                  type: string
                default: []
              type:
                type: string
              lifecycle:
                type: string
              owner:
                type: string
              dependecies:
                type: array
                items:
                  type: string
                default: []
            required:
              - type
              - lifecycle
              - owner
              - system
              - application
        required:
          - spec
