apiVersion: api.catcode.io/v1alpha1
kind: ResourceDefinition
metadata: 
  name: ComponentResourceDefinition
spec:
  group: core.catcode.io
  names:
    plural: components
    singular: component
    kind: Component
  versions: 
    - name: v1alpha1
      schemaVersion: openAPISchemaV3
      schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              system:
                type: string
              application:
                type: string
              tags:
                type: array
                items:
                  type: string
              type:
                type: string
              lifecycle:
                type: string
              owner:
                type: string
              dependecies:
                type: array
                items:
                  type: string
            required:
              - type
              - lifecycle
              - owner
              - dependecies
              - system
              - aplication
      required:
        - spec
