apiVersion: api.catcode.io/v1alpha1
kind: ResourceDefinition
metadata: 
  name: SystemResourceDefinition
spec:
  group: templating.catcode.io
  names:
    plural: systems
    singular: system
    kind: System
  versions: 
    - name: v1alpha1
      schemaVersion: openAPISchemaV3
      schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              owner:
                type: string
              description:
                type: string
            required:
              - owner
        required:
          - spec
