apiVersion: customresource.catcode.mw/v1alpha1
kind: ResourceDefinition
metadata: 
  name: SystemResourceDefinition
spec:
  group: templating.catcode.mw
  names:
    plural: systems
    singular: system
    kind: System
  versions: 
    - name: v1alpha1
      schema:
        openAPISchemaV3:
          type: object
          properties:
            apiVersion:
              type: "string"
            kind:
              type: "string"
              const: "System"
            metadata:
              type: "object"
              properties:
                name:
                  type: "string"
                description:
                  type: "string"
              required:
                - name
                - description
            spec:
              type: "object"
              properties:
                owner:
                  type: "string"
              required:
                - owner
          required:
            - apiVersion
            - kind
            - metadata
            - spec
