apiVersion: api.catcode.io/v1alpha1
kind: ResourceDefinition
metadata: 
  name: TemplateResourceDefinition
spec:
  group: templating.catcode.io
  names: 
    plural: templates
    singular: template
    kind: Template
  versions: 
    - name: v1alpha1
      schema:
        openAPISchemaV3:
          type: object
          properties:
            spec:
              type: "object"
              properties:
                parameters:
                  type: "object"
                  description: "json schema"
                steps:
                  type: "object"
              required:
                - parameters
          required:
            - apiVersion
            - kind
            - metadata
            - spec
