apiVersion: api.catcode.io/v1alpha1
kind: ResourceDefinition
metadata: 
  name: TemplateResourceDefinition
spec:
  group: templating.catcode.io
  names: 
    plural: templates
    singular: template
    kind: Template
  versions: 
    - name: v1alpha1
      schemaVersion: openAPISchemaV3
      schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                description: "json schema"
                nullable: true
              steps:
                type: object
                nullable: true
            required:
              - parameters
              - steps
        required:
          - spec
