apiVersion: api.catcode.io/v1alpha1
kind: ResourceDefinition
metadata: 
  name: UserResourceDefinition
spec:
  group: templating.catcode.io
  names:
    plural: users
    singular: user
    kind: User
  versions: 
    - name: v1alpha1
      schemaVersion: openAPISchemaV3
      schema:
        type: object
        properties:
          spec:
            type: object
            required: []
        required:
          - spec
