apiVersion: api.catcode.io/v1alpha1
kind: ResourceDefinition
metadata: 
  name: UserResourceDefinition
spec:
  group: catcode.io
  names:
    plural: users
    singular: user
    kind: User
  versions: 
    - name: v1alpha1
      schemaVersion: openAPISchemaV3
      schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              profile:
                type: object
                properties:
                  email:
                    type: ['string', 'null']
                    description: Email where the user can be reached.
                  displayName:
                    type: ['string', 'null']
                    description: A name for the user
                  image:
                    type: ['string', 'null']
                    description: The url of a picture representing the user 
              memberOf:
                type: array
                description: A list of groups that the user is a member of
                items:
                  type: string
                default: []
            required:
              - memberOf
              - profile
        required:
          - spec
