apiVersion: customresource.catcode.mw/v1alpha1
kind: ResourceDefinition
metadata: 
  name: UserResourceDefinition
spec:
  group: templating.catcode.mw
  plural: users
  singular: user
  kind: User
  versions: 
    - name: v1alpha1
      schema:
        openAPISchemaV3:
          apiVersion:
            type: "string"
          kind:
            type: "string"
            const: "User"
          metadata:
            type: "object"
            properties:
              name:
                type: "string"
            required:
              - name
          spec:
            type: "object"
            required: []
        required:
          - apiVersion
          - kind
          - metadata
